name: CI/CD Pipeline

on:
  push:
    branches:
      - pipeline

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ECR
        run: $(aws ecr get-login --no-include-email --region eu-central-1)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and Push Docker Images
        run: |
          docker build -t my-backend:latest .
          docker tag my-backend:latest public.ecr.aws/p2c4r2s8/eschool/my-backend:latest
          docker push public.ecr.aws/p2c4r2s8/eschool/my-backend:latest